-- Weather Observation Station 2
SELECT ROUND(SUM(LAT_N),2) AS LAT,  
ROUND(SUM(LONG_W),2) AS LON
FROM STATION;

-- Weather Observation Station 13
SELECT ROUND(SUM(LAT_N), 4) AS SUM_LATN FROM STATION
WHERE LAT_N BETWEEN 38.7880 AND 137.2345;

-- Weather Observation Station 14
SELECT ROUND(MAX(LAT_N),4) FROM STATION
WHERE LAT_N < 137.2345;

-- Weather Observation Station 15
SELECT ROUND(LONG_W, 4) FROM STATION
WHERE LAT_N < 137.2345
ORDER BY LAT_N DESC 
LIMIT 1;

-- Weather Observation Station 16
SELECT ROUND(MIN(LAT_N), 4) FROM STATION
WHERE LAT_N > 38.7780;