-- Average Population of Each Continent
SELECT CO.CONTINENT, FLOOR(AVG(CI.POPULATION)) AS AVERAGE_POP FROM COUNTRY CO
JOIN CITY CI
ON CI.COUNTRYCODE = CO.CODE
GROUP BY CO.CONTINENT
ORDER BY AVERAGE_POP;