-- Challenges
WITH ChallengeCounts AS (
    SELECT
        H.HACKER_ID,
        H.NAME,
        COUNT(*) AS NUM_CHALLENGES,
        RANK() OVER (ORDER BY COUNT(*) DESC) AS RANK,
        COUNT(*) OVER (PARTITION BY COUNT(*)) AS COUNT
    FROM HACKERS H
    JOIN CHALLENGES CH ON H.HACKER_ID = CH.HACKER_ID
    GROUP BY H.HACKER_ID, H.NAME
)

SELECT HACKER_ID, NAME, NUM_CHALLENGES
FROM ChallengeCounts
WHERE RANK = 1 OR COUNT = 1
ORDER BY NUM_CHALLENGES DESC, HACKER_ID;