-- Ollivander's Inventory
SELECT ID, AGE, COINS_NEEDED, POWER
FROM (
    SELECT
        WANDS.ID,
        WANDS_PROPERTY.AGE,
        WANDS.COINS_NEEDED,
        WANDS.POWER,
        COINRANKING = ROW_NUMBER() OVER (PARTITION BY WANDS.POWER, WANDS_PROPERTY.AGE
                                        ORDER BY WANDS.COINS_NEEDED)
    FROM
        WANDS
        INNER JOIN WANDS_PROPERTY ON WANDS.CODE = WANDS_PROPERTY.CODE
    WHERE
        WANDS_PROPERTY.IS_EVIL = 0
) AS SUBQUERY
WHERE COINRANKING = 1
ORDER BY POWER DESC, AGE DESC;

SELECT W.ID, WP.AGE, W.COINS_NEEDED, 