-- the report

SELECT CASE
           WHEN G.GRADE >= 8 THEN STU.NAME
           ELSE "NULL"
       END,
       G.GRADE,
       STU.MARKS
FROM STUDENTS STU
JOIN GRADES G ON STU.MARKS BETWEEN G.MIN_MARK AND G.MAX_MARK
ORDER BY G.GRADE DESC,
         STU.NAME;