-- Top Competitors
SELECT H.HACKER_ID,
       H.NAME
FROM HACKERS H
LEFT JOIN SUBMISSIONS SU ON H.HACKER_ID = SU.HACKER_ID
LEFT JOIN CHALLENGES CH ON SU.CHALLENGE_ID = CH.CHALLENGE_ID
LEFT JOIN DIFFICULTY DI ON CH.DIFFICULTY_LEVEL = DI.DIFFICULTY_LEVEL
WHERE SU.SCORE = DI.SCORE
GROUP BY H.HACKER_ID,
         H.NAME
HAVING COUNT(SU.CHALLENGE_ID) > 1
ORDER BY COUNT(SU.CHALLENGE_ID) DESC, H.HACKER_ID ASC;